<a href="https://colab.research.google.com/github/danish123-a/Cancer_Detection_With_DataLoader_Using_ANN/blob/main/Cancer_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import numpy as np

In [127]:
import pandas as pd

In [128]:
from sklearn.model_selection import train_test_split

In [129]:
from sklearn.preprocessing import StandardScaler

In [130]:
from sklearn.preprocessing import LabelEncoder

In [131]:
v=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")


In [132]:
v

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [133]:
v=v.drop(columns=["id","Unnamed: 32"])

In [134]:
v

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [135]:
x_train,x_test,y_train,y_test=train_test_split(v.iloc[:,1:],v.iloc[:,0],test_size=0.2)

In [136]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
164       23.270         22.04          152.10     1686.0          0.08439   
270       14.290         16.82           90.30      632.6          0.06429   
152        9.731         15.34           63.78      300.2          0.10720   
399       11.800         17.26           75.26      431.9          0.09087   
419       11.160         21.41           70.95      380.3          0.10180   
..           ...           ...             ...        ...              ...   
14        13.730         22.61           93.60      578.3          0.11310   
20        13.080         15.71           85.63      520.0          0.10750   
256       19.550         28.77          133.60     1207.0          0.09260   
427       10.800         21.98           68.79      359.9          0.08801   
92        13.270         14.76           84.74      551.7          0.07355   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
164           0.11450        0.132400              0.09702         0.1801   
270           0.02675        0.007250              0.00625         0.1508   
152           0.15990        0.410800              0.07857         0.2548   
399           0.06232        0.028530              0.01638         0.1847   
419           0.05978        0.008955              0.01076         0.1615   
..                ...             ...                  ...            ...   
14            0.22930        0.212800              0.08025         0.2069   
20            0.12700        0.045680              0.03110         0.1967   
256           0.20630        0.178400              0.11440         0.1893   
427           0.05743        0.036140              0.01404         0.2016   
92            0.05055        0.032610              0.02648         0.1386   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
164                 0.05553  ...         28.01          28.22   
270                 0.05376  ...         14.91          20.65   
152                 0.09296  ...         11.02          19.49   
399                 0.06019  ...         13.45          24.49   
419                 0.06144  ...         12.36          28.92   
..                      ...  ...           ...            ...   
14                  0.07682  ...         15.03          32.01   
20                  0.06811  ...         14.50          20.49   
256                 0.06232  ...         25.05          36.27   
427                 0.05977  ...         12.76          32.04   
92                  0.05318  ...         16.36          22.35   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
164           184.20      2403.0           0.12280            0.35830   
270            94.44       684.6           0.08567            0.05036   
152            71.04       380.5           0.12920            0.27720   
399            86.00       562.0           0.12440            0.17260   
419            79.26       458.0           0.12820            0.11080   
..               ...         ...               ...                ...   
14            108.80       697.7           0.16510            0.77250   
20             96.09       630.5           0.13120            0.27760   
256           178.60      1926.0           0.12810            0.53290   
427            83.69       489.5           0.13030            0.16960   
92            104.50       830.6           0.10060            0.12380   

     concavity_worst  concave points_worst  symmetry_worst  \
164          0.39480               0.23460          0.3589   
270          0.03866               0.03333          0.2458   
152          0.82160               0.15710          0.3108   
399          0.14490               0.05356          0.2779   
419          0.03582               0.04306          0.2976   
..               ...                   ...             ...   
14           0.69430               0.22080         

In [137]:
y_train

164    M
270    B
152    B
399    B
419    B
      ..
14     M
20     B
256    M
427    B
92     B
Name: diagnosis, Length: 455, dtype: object

In [138]:
std=StandardScaler()

In [139]:
x_train,x_test=std.fit_transform(x_train),std.fit_transform(x_test)

In [140]:
label=LabelEncoder()

In [141]:
y_train,y_test=label.fit_transform(y_train),label.fit_transform(y_test)

In [142]:
y_train

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [143]:
import torch as t

In [144]:
import numpy as np

In [145]:
x_train_t,x_test_t,y_train_t,y_test_t=t.from_numpy(x_train.astype(np.float32)),t.from_numpy(x_test.astype(np.float32)),t.from_numpy(y_train.astype(np.float32)),t.from_numpy(y_test.astype(np.float32))

In [146]:
x_train_t

tensor([[ 2.5773,  0.7196,  2.4638,  ...,  1.8412,  1.1441,  0.4763],
        [ 0.0479, -0.5592, -0.0652,  ..., -1.2276, -0.7521, -1.3058],
        [-1.2361, -0.9218, -1.1505,  ...,  0.6596,  0.3377,  2.4535],
        ...,
        [ 1.5295,  2.3683,  1.7067,  ...,  1.2237, -0.1485,  0.9777],
        [-0.9351,  0.7049, -0.9455,  ..., -0.5945,  0.0979, -0.4098],
        [-0.2393, -1.0639, -0.2928,  ..., -0.2095, -1.4747, -1.2558]])

In [147]:
import torch as t

In [153]:
from torch.utils.data import Dataset,DataLoader

In [158]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels
  def __len__(self):
    return (self.features.shape[0])
  def __getitem__(self,idx):
      return self.features[idx],self.labels[idx]

In [159]:

dataset_train_t=CustomDataset(x_train_t,y_train_t)
dataset_train_t[0]


(tensor([ 2.5773,  0.7196,  2.4638,  2.9059, -0.8683,  0.2065,  0.5683,  1.2561,
         -0.0776, -1.0358,  0.9583, -0.6506,  0.8835,  1.2473, -0.7022,  0.0176,
         -0.1001,  0.7323, -0.1252, -0.0214,  2.4321,  0.4538,  2.3043,  2.6603,
         -0.4424,  0.7058,  0.6266,  1.8412,  1.1441,  0.4763]),
 tensor(1.))

In [160]:
dataset_test_t=CustomDataset(x_test_t,y_test_t)

In [161]:
dataset_train_t_loader=DataLoader(dataset_train_t,batch_size=32,shuffle=True)


In [162]:
dataset_test_t_loader=DataLoader(dataset_test_t,batch_size=32,shuffle=True)

In [163]:
import torch.nn as nn

In [164]:
class Simple_nn(nn.Module):
  def __init__(self,features):
    super().__init__()
    self.container=nn.Sequential(nn.Linear(features,1),nn.Sigmoid())
  def forward(self,x):
    z=self.container(x)
    return z


In [165]:
#x_train_t,x_test_t,y_train_t,y_test_t=x_train_t.float(),x_test_t.float(),y_train_t.float(),y_test_t.float()

In [166]:
model=Simple_nn(x_train_t.shape[1])

In [167]:
model(x_train_t)

tensor([[0.5136],
        [0.3324],
        [0.7436],
        [0.3902],
        [0.5024],
        [0.5753],
        [0.4109],
        [0.6680],
        [0.5336],
        [0.5245],
        [0.4407],
        [0.5397],
        [0.3516],
        [0.3228],
        [0.3832],
        [0.5017],
        [0.4307],
        [0.4232],
        [0.4361],
        [0.6257],
        [0.4499],
        [0.4201],
        [0.4297],
        [0.5736],
        [0.3239],
        [0.5757],
        [0.4828],
        [0.3186],
        [0.5063],
        [0.3760],
        [0.4212],
        [0.4311],
        [0.5423],
        [0.4768],
        [0.7429],
        [0.5070],
        [0.4298],
        [0.5898],
        [0.5799],
        [0.5497],
        [0.5441],
        [0.4799],
        [0.4747],
        [0.3817],
        [0.4685],
        [0.4699],
        [0.4812],
        [0.5424],
        [0.4014],
        [0.4425],
        [0.5572],
        [0.4241],
        [0.6098],
        [0.5673],
        [0.4950],
        [0

In [168]:
loss1=nn.BCELoss()

In [169]:
#ptimmizer
optimizer=t.optim.SGD(model.parameters(),lr=0.01)

In [170]:
epochs=25

In [171]:
batch_size=32


In [172]:
for i in range(epochs):
  for batch_features,batch_label in dataset_train_t_loader:
    #forward_pass
    y_pred=model(batch_features)
    #loss
    loss_=loss1(y_pred,batch_label.reshape(-1,1))
    #clear gradient
    optimizer.zero_grad()
    #backward()
    loss_.backward()
    #update weights
    optimizer.step()
    print(loss_)

tensor(0.6318, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5901, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5670, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5996, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6020, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5594, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5844, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5433, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5346, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5728, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5508, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5460, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4776, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5287, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6057, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4362, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5136, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4793, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4822, grad_fn=<Bina

In [173]:
model(x_train_t)

tensor([[0.9989],
        [0.0225],
        [0.3014],
        [0.0519],
        [0.0490],
        [0.2187],
        [0.7959],
        [0.0055],
        [0.9769],
        [0.9334],
        [0.9645],
        [0.2905],
        [0.0428],
        [0.0097],
        [0.4924],
        [0.9999],
        [0.0132],
        [0.3867],
        [0.9650],
        [0.9963],
        [0.6404],
        [0.0553],
        [0.0579],
        [0.9749],
        [0.0151],
        [0.0472],
        [0.9981],
        [0.0438],
        [0.6786],
        [0.0624],
        [0.0599],
        [0.0213],
        [0.0173],
        [0.9959],
        [0.9739],
        [0.0327],
        [0.9352],
        [0.1052],
        [0.0152],
        [0.2789],
        [0.9907],
        [0.1448],
        [0.7288],
        [0.0259],
        [0.0932],
        [0.1252],
        [0.7730],
        [0.9214],
        [0.0124],
        [0.0167],
        [0.0317],
        [0.0132],
        [0.2189],
        [0.9914],
        [0.2244],
        [0

In [176]:
model.eval()
accuracy1=[]
#evaluation
with t.no_grad():
  for batch_features,batch_label in dataset_test_t_loader:
    #forward
    y_pred=model(batch_features)
    y_pred=(y_pred>0.8).float()
    #accuracy
    batch_accuracy=((y_pred==batch_label.reshape(-1,1)).float()).mean()
    accuracy1.append(batch_accuracy)

In [177]:
accuracy1

[tensor(0.9688), tensor(0.9688), tensor(1.), tensor(0.8333)]

In [180]:
#overall_accuracy
overall_accuracy=sum(accuracy1)/len(accuracy1)
print(f'overall_accuracy:{overall_accuracy}')

overall_accuracy:0.9427083134651184
